# Day-15 Assignment:

In [1]:
import numpy as np

In [2]:
from numpy import array

## 1. Create a 3x3x3 array with random values

In [3]:
arr1 = np.empty([3,3,3])
print(arr1)
print("Shape = ",arr1.shape)

[[[4.67296746e-307 1.69121096e-306 7.56595733e-307]
  [1.95819673e-306 7.56599807e-307 8.90104239e-307]
  [1.24610383e-306 1.69118108e-306 8.06632139e-308]]

 [[1.20160711e-306 1.69119330e-306 1.29062229e-306]
  [1.60217812e-306 1.37961370e-306 8.01091099e-307]
  [1.02359848e-306 1.60219035e-306 1.60220393e-306]]

 [[1.05700515e-307 1.11261774e-306 1.29060871e-306]
  [8.34424766e-308 8.34445138e-308 1.37959129e-306]
  [1.02360528e-306 9.79103797e-307 2.46155235e-312]]]
Shape =  (3, 3, 3)


## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
x = np.zeros([5,5])
x[1][0] = 1
x[2][1] = 2
x[3][2] = 3
x[4][3] = 4
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
import random
arr2 = np.zeros([8,8],dtype = int)
num = 1
for i in range(0,8):
    for j in range(0,8,2):
        if(i%2 == 0):
            arr2[i][j] = num
        else:
            arr2[i][j+1] = num
        num = random.randint(1,9)
print(arr2)

[[1 0 1 0 8 0 8 0]
 [0 3 0 4 0 8 0 2]
 [3 0 3 0 2 0 2 0]
 [0 7 0 9 0 6 0 1]
 [1 0 4 0 7 0 9 0]
 [0 2 0 2 0 5 0 8]
 [3 0 4 0 5 0 1 0]
 [0 9 0 5 0 4 0 8]]


## 4. Normalize a 5x5 random matrix

In [6]:
arr4 = np.random.random((5,5))
print("Matrix before : ")
print(arr4)
normalized_mat = (arr4 - np.min(arr4))/np.ptp(arr4)
print("Matrix After normalization : ")
print(normalized_mat)

Matrix before : 
[[0.47545417 0.73906334 0.21018873 0.58327294 0.60636611]
 [0.80798939 0.75563952 0.33933253 0.08381875 0.84804437]
 [0.8386547  0.40404455 0.43084177 0.89091044 0.53866504]
 [0.06025865 0.36186572 0.21373072 0.44161663 0.14615332]
 [0.16204189 0.97286152 0.74670549 0.30322213 0.26308379]]
Matrix After normalization : 
[[0.4549575  0.7438117  0.16428842 0.57310173 0.59840646]
 [0.81933858 0.76197532 0.30579991 0.02581638 0.86322949]
 [0.85294061 0.3767092  0.40607271 0.91020072 0.52422188]
 [0.         0.33049104 0.16816961 0.41787944 0.09412054]
 [0.11153071 1.         0.75218571 0.26623134 0.22224907]]


## 5. How to find common values between two arrays?

##### -Common values can be found using numpy function - np.intersect1d(array1,array2) 

In [15]:
a1 = array([[1,2,3],[20,25,30],[15,10,37]])
a2 = array([[1,5,20],[7,8,37],[4,6,10]])
print("Array1 :")
print(a1)
print("Array2 :")
print(a2)
print("Common values between these two :")
print(np.intersect1d(a1,a2))

Array1 :
[[ 1  2  3]
 [20 25 30]
 [15 10 37]]
Array2 :
[[ 1  5 20]
 [ 7  8 37]
 [ 4  6 10]]
Common values between these two :
[ 1 10 20 37]


## 6.How to get the dates of yesterday, today and tomorrow?

##### 1). To get todays date we use  : np.datetime64('today', 'D')                                          
##### 2). For yesterday's date we subtract today by 1 day using : np.timedelta64(1, 'D')                   
##### 3). For tomorrow's date we add today by 1 day using : np.timedelta64(1, 'D')                   

In [29]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


## 7. Consider two random array A and B, check if they are equal

In [34]:
A = array([[10,20],[15,37],[25,50]])
B = array([[10,30],[30,37],[45,50]])
print("A :")
print(A)
print("B :")
print(B)
print("Comparision :")
print(A == B)

A :
[[10 20]
 [15 37]
 [25 50]]
B :
[[10 30]
 [30 37]
 [45 50]]
Comparision :
[[ True False]
 [False  True]
 [False  True]]


## 8.Create random vector of size 10 and replace the maximum value by 0

In [56]:
vect = np.empty(6,dtype = int)
print("Initial vector :")
print(vect,"\n")
place = np.where(vect == vect.max())
vect[place] = 0 
print("After replacing :")
print(vect)

Initial vector :
[10 30 30  0 45 50] 

After replacing :
[10 30 30  0 45  0]


## 9. How to print all the values of an array?

##### -By using nested for loop.

In [65]:
new_array = array([[1,2,3],[4,5,6],[7,8,9]])
for i in new_array:
    for j in i:
        print(j,end="   ")

1   2   3   4   5   6   7   8   9   

## 10.Subtract the mean of each row of a matrix

In [93]:
arry7 = array([[1,2,3],[4,5,6],[7,8,9]])
print("Initial array :")
print(arry7)
SUB_arry = arry7 - arry7.mean(axis=1) 
print("After subtraction :")
print(SUB_arry)

Initial array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After subtraction :
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [101]:
vet1 = array([10,20,30,40,50,60,70,80,90,10])
print("Original vector : ")
print(vet1,"\n")
vet2 = array([0,6,8,6])                  #given indices   in vetor 2

for i in np.unique(vet2):                #iterate only on unique indices to avoid multiple time addition
    vet1[i] = vet1[i] + 1
    
    
print("After adding 1 to given indices :")
print(vet1)

Original vector : 
[10 20 30 40 50 60 70 80 90 10] 

After adding 1 to given indices :
[11 20 30 40 50 60 71 80 91 10]


## 12.How to get the diagonal of a dot product?

##### -To find dot product use - numpy.dot(array1,array2)
##### -diagonal can be obtained by using  -numpy.diagonal(array)

In [113]:
v1 = array([[1,2,3],[4,5,4],[6,7,8]])
v2 = array([[4,5,2],[2,1,3],[8,3,7]])
dotP = np.dot(v1,v2)
print("Dot product = ")
print(dotP,"\n\n")
print("Diagonal of dot product = ")
print(np.diagonal(dotP))


Dot product = 
[[ 32  16  29]
 [ 58  37  51]
 [102  61  89]] 


Diagonal of dot product = 
[32 37 89]


## 13.How to find the most frequent value in an array?

##### -by using the function of numpy - np.bincount(array).argmax()

In [125]:
my_arry = array([60,80,37,25,37,40,37,26,32])
freq = np.bincount(my_arry).argmax()
print("Most frequent value =  ",freq)

Most frequent value =   37


## 14.How to get the n largest values of an array

In [147]:
ww = array([10,100,8,50,25,37,40,80,100,101,15,14,4])
print("Given array :")
print(ww,"\n")
new = np.unique(ww)
new1 = np.sort(new)
n = int(input("Enter the n value : "))
print("\nThe",n,"largest values of given array are :")
print(new1[-n:])

Given array :
[ 10 100   8  50  25  37  40  80 100 101  15  14   4] 

Enter the n value : 2

The 2 largest values of given array are :
[100 101]


## 15.How to create a record array from a regular array?

##### -By using - np.core.records.fromarrays([arrays],names=' ')

In [151]:
Ar1 = array([1,2,3,4])
Ar2 = array(['Apple','Orange','PineApple','Watermelon'])
Ar3 = array([2,5,1,3])
print("Array1 = ",Ar1,"\nArray2 = ",Ar2,"\nArray3 = ",Ar3)
Record_arry = np.core.records.fromarrays([Ar1,Ar2,Ar3])
print("\n\nRecorded Array = ",Record_arry)


Array1 =  [1 2 3 4] 
Array2 =  ['Apple' 'Orange' 'PineApple' 'Watermelon'] 
Array3 =  [2 5 1 3]


Recorded Array =  [(1, 'Apple', 2) (2, 'Orange', 5) (3, 'PineApple', 1) (4, 'Watermelon', 3)]


## ----------------------------------------------------------------------------------------------------------------------------------